=== nuncio-bitis/SigGen/data/SequenceDesc.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Define the XML document type of Sequence -->
<!DOCTYPE Sequence [
  <!ELEMENT Sequence (Name,Description,SampleRate,Sequence*,Signal*,DTMF*,Silence*)>

  <!ELEMENT Name (#PCDATA)>
  <!ELEMENT Description (#PCDATA)>
  <!ELEMENT SampleRate (#PCDATA)>
  <!ELEMENT Silence (#PCDATA)>

  <!ELEMENT DTMF (#PCDATA,OnTime,OffTime)>
    <!ELEMENT OnTime (#PCDATA)>
    <!ELEMENT OffTime (#PCDATA)>

  <!ELEMENT Signal (Duration?,Samples?,RiseFactor?,FallFactor?,Tone)>
      <!ELEMENT Duration (#PCDATA)>         <!-- Duration: in milliseconds -->
      <!ELEMENT Samples (#PCDATA)>          <!-- Number of samples (only if Duration not specified) -->
      <!ELEMENT RiseFactor (#PCDATA)>       <!-- Rise and Fall factors: percentage of the duration -->
      <!ELEMENT FallFactor (#PCDATA)>
      <!ELEMENT Tone (amp,freq,phase,harmonics?,harmonicAmps?)>
          <!ELEMENT amp (#PCDATA)>          <!-- Amplitude of fundamental frequency -->
          <!ELEMENT freq (#PCDATA)>
          <!ELEMENT phase (#PCDATA)>
          <!ELEMENT harmonics (#PCDATA)>    <!-- harmonics: List of harmonics. 1 (the fundamental) is implied above -->
          <!ELEMENT harmonicAmps (#PCDATA)> <!-- harmonics: List of harmonics' amplitudes -->
]>
<BODY></BODY>

=== nuncio-bitis/SigGen/data/Seq1_desc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Sequence SYSTEM "SequenceDesc.dtd">
<Sequence>
    <Name>Sequence_1</Name>
    <Description>Sequence #1</Description>
    <SampleRate>16000</SampleRate>

    <DTMF>
        *16175551212#
        <OnTime>75</OnTime>
        <OffTime>75</OffTime>
    </DTMF>

    <Silence>250</Silence>

    <Signal>
        <Name>Signal 1</Name>
        <Description>Signal #1</Description>
        <Duration>1000</Duration>
        <Tone>
            <amp>1.0</amp>
            <freq>1200</freq>
            <phase>0</phase>
        </Tone>
        <Tone>
            <amp>2.0</amp>
            <freq>1800</freq>
            <phase>90</phase>
        </Tone>
        <Tone>
            <amp>1.0</amp>
            <freq>2100</freq>
            <phase>180</phase>
        </Tone>
        <Tone>
            <amp>2.0</amp>
            <freq>2400</freq>
            <phase>270</phase>
        </Tone>
    </Signal>
</Sequence>

=== nuncio-bitis/SigGen/data/B_desc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Sequence SYSTEM "SequenceDesc.dtd">
<Sequence>
    <Name>Modem_B</Name>
    <Description>Modem B tone.</Description>
    <Signal>
        <Name>Modem_B</Name>
        <Description>Modem B tone.</Description>
        <SampleRate>16000</SampleRate>
        <Duration>1000</Duration>
        <Tone>
            <amp>1.0</amp>
            <freq>1200</freq>
            <phase>0</phase>
        </Tone>
    </Signal>
</Sequence>

=== nuncio-bitis/SigGen/data/PerfLow_desc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Sequence SYSTEM "SequenceDesc.dtd">
<Sequence>
    <Name>alarm-low</Name>
    <Description>Perfusion alarm, low priority.</Description>
    <SampleRate>16000</SampleRate>

    <Signal>
        <Name>Pulse 2</Name>
        <Description>Piano E4</Description>
        <Duration>250</Duration>
        <RiseFactor>10.0</RiseFactor>
        <FallFactor>30.0</FallFactor>
        <Tone>
            <freq>329.63</freq>
            <amp>0.5</amp>
            <phase>0</phase>
            <harmonics>2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17</harmonics>
            <harmonicAmps>0.25119,0.00794,0.01585,0.03162,0.03162,0.02512,0.01000,0.00032,0.00316,0.00158,0.00158,0.00010,0.00158,0.00010,0.00003,0.00006</harmonicAmps>
        </Tone>
    </Signal>

    <Silence>200</Silence>

    <Signal>
        <Name>Pulse 1</Name>
        <Description>Piano C4</Description>
        <Duration>250</Duration>
        <RiseFactor>10.0</RiseFactor>
        <FallFactor>30.0</FallFactor>
        <Tone>
            <freq>261.63</freq>
            <amp>0.5</amp>
            <phase>0</phase>
            <harmonics>2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17</harmonics>
            <harmonicAmps>0.25119,0.00794,0.01585,0.03162,0.03162,0.02512,0.01000,0.00032,0.00316,0.00158,0.00158,0.00010,0.00158,0.00010,0.00003,0.00006</harmonicAmps>
        </Tone>
    </Signal>

</Sequence>

=== nuncio-bitis/SigGen/data/SIT_desc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Sequence SYSTEM "SequenceDesc.dtd">
<Sequence>
    <Name>SIT</Name>
    <Description>SIT Intercept - Number changed or disconnected</Description>
    <SampleRate>16000</SampleRate>

    <Silence>100</Silence>

    <Signal>
        <Name>Tone_1</Name>
        <Description>Tone #1</Description>
        <Duration>330</Duration>
        <Tone>
            <amp>1.0</amp>
            <freq>950.0</freq>
            <phase>0</phase>
        </Tone>
    </Signal>

    <Silence>30</Silence>

    <Signal>
        <Name>Tone_2</Name>
        <Description>Tone #2</Description>
        <Duration>330</Duration>
        <Tone>
            <amp>1.0</amp>
            <freq>1400.0</freq>
            <phase>0</phase>
        </Tone>
    </Signal>

    <Silence>30</Silence>

    <Signal>
        <Name>Tone_3</Name>
        <Description>Tone #3</Description>
        <Duration>330</Duration>
        <Tone>
            <amp>1.0</amp>
            <freq>1800.0</freq>
            <phase>0</phase>
        </Tone>
    </Signal>

    <Silence>100</Silence>
</Sequence>

=== nuncio-bitis/SigGen/data/A_desc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Sequence SYSTEM "SequenceDesc.dtd">
<Sequence>
    <Name>Modem_A</Name>
    <Description>Modem A tone.</Description>
	<Signal>
	    <Name>Modem_A</Name>
	    <Description>Modem A tone.</Description>
	    <SampleRate>16000</SampleRate>
	    <Duration>1000</Duration>
        <Tone>
            <amp>1.0</amp>
            <freq>1800</freq>
            <phase>0</phase>
        </Tone>
        <Tone>
            <amp>1.0</amp>
            <freq>2400</freq>
            <phase>0</phase>
        </Tone>
	</Signal>
</Sequence>

=== nuncio-bitis/SigGen/data/C4-Maj_desc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Sequence SYSTEM "SequenceDesc.dtd">
<Sequence>
    <Name>C4-Maj</Name>
    <Description>Approximation of notes on a piano. C4 major scale.</Description>
    <SampleRate>16000</SampleRate>

    <Signal>
        <Name>C4</Name>
        <Description>Piano C4</Description>
        <Duration>250</Duration>
        <RiseFactor>10.0</RiseFactor>
        <FallFactor>70.0</FallFactor>
        <Tone>
            <freq>261.63</freq>
            <amp>0.5</amp>
            <phase>0</phase>
            <harmonics>2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17</harmonics>
            <harmonicAmps>0.25119,0.00794,0.01585,0.03162,0.03162,0.02512,0.01000,0.00032,0.00316,0.00158,0.00158,0.00010,0.00158,0.00010,0.00003,0.00006</harmonicAmps>
        </Tone>
    </Signal>

    <Silence>125</Silence>

    <Signal>
        <Name>D4</Name>
        <Description>Piano D4</Description>
        <Duration>250</Duration>
        <RiseFactor>10.0</RiseFactor>
        <FallFactor>70.0</FallFactor>
        <Tone>
            <freq>293.66</freq>
            <amp>0.5</amp>
            <phase>0</phase>
            <harmonics>2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17</harmonics>
            <harmonicAmps>0.25119,0.00794,0.01585,0.03162,0.03162,0.02512,0.01000,0.00032,0.00316,0.00158,0.00158,0.00010,0.00158,0.00010,0.00003,0.00006</harmonicAmps>
        </Tone>
    </Signal>

    <Silence>125</Silence>

    <Signal>
        <Name>E4</Name>
        <Description>Piano E4</Description>
        <Duration>250</Duration>
        <RiseFactor>10.0</RiseFactor>
        <FallFactor>70.0</FallFactor>
        <Tone>
            <freq>329.63</freq>
            <amp>0.5</amp>
            <phase>0</phase>
            <harmonics>2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17</harmonics>
            <harmonicAmps>0.25119,0.00794,0.01585,0.03162,0.03162,0.02512,0.01000,0.00032,0.00316,0.00158,0.00158,0.00010,0.00158,0.00010,0.00003,0.00006</harmonicAmps>
        </Tone>
    </Signal>

    <Silence>125</Silence>

    <Signal>
        <Name>F4</Name>
        <Description>Piano F4</Description>
        <Duration>250</Duration>
        <RiseFactor>10.0</RiseFactor>
        <FallFactor>70.0</FallFactor>
        <Tone>
            <freq>349.23</freq>
            <amp>0.5</amp>
            <phase>0</phase>
            <harmonics>2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17</harmonics>
            <harmonicAmps>0.25119,0.00794,0.01585,0.03162,0.03162,0.02512,0.01000,0.00032,0.00316,0.00158,0.00158,0.00010,0.00158,0.00010,0.00003,0.00006</harmonicAmps>
        </Tone>
    </Signal>

    <Silence>125</Silence>

    <Signal>
        <Name>G4</Name>
        <Description>Piano G4</Description>
        <Duration>250</Duration>
        <RiseFactor>10.0</RiseFactor>
        <FallFactor>70.0</FallFactor>
        <Tone>
            <freq>392.00</freq>
            <amp>0.5</amp>
            <phase>0</phase>
            <harmonics>2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17</harmonics>
            <harmonicAmps>0.25119,0.00794,0.01585,0.03162,0.03162,0.02512,0.01000,0.00032,0.00316,0.00158,0.00158,0.00010,0.00158,0.00010,0.00003,0.00006</harmonicAmps>
        </Tone>
    </Signal>

    <Silence>125</Silence>

    <Signal>
        <Name>A4</Name>
        <Description>Piano A4</Description>
        <Duration>250</Duration>
        <RiseFactor>10.0</RiseFactor>
        <FallFactor>70.0</FallFactor>
        <Tone>
            <freq>440.00</freq>
            <amp>0.5</amp>
            <phase>0</phase>
            <harmonics>2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17</harmonics>
            <harmonicAmps>0.25119,0.00794,0.01585,0.03162,0.03162,0.02512,0.01000,0.00032,0.00316,0.00158,0.00158,0.00010,0.00158,0.00010,0.00003,0.00006</harmonicAmps>
        </Tone>
    </Signal>

    <Silence>125</Silence>

    <Signal>
        <Name>B4</Name>
        <Description>Piano B4</Description>
        <Duration>250</Duration>
        <RiseFactor>10.0</RiseFactor>
        <FallFactor>70.0</FallFactor>
        <Tone>
            <freq>493.88</freq>
            <amp>0.5</amp>
            <phase>0</phase>
            <harmonics>2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17</harmonics>
            <harmonicAmps>0.25119,0.00794,0.01585,0.03162,0.03162,0.02512,0.01000,0.00032,0.00316,0.00158,0.00158,0.00010,0.00158,0.00010,0.00003,0.00006</harmonicAmps>
        </Tone>
    </Signal>

    <Silence>125</Silence>

    <Signal>
        <Name>C5</Name>
        <Description>Piano C5</Description>
        <Duration>250</Duration>
        <RiseFactor>10.0</RiseFactor>
        <FallFactor>70.0</FallFactor>
        <Tone>
            <freq>523.25</freq>
            <amp>0.5</amp>
            <phase>0</phase>
            <harmonics>2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17</harmonics>
            <harmonicAmps>0.25119,0.00794,0.01585,0.03162,0.03162,0.02512,0.01000,0.00032,0.00316,0.00158,0.00158,0.00010,0.00158,0.00010,0.00003,0.00006</harmonicAmps>
        </Tone>
    </Signal>

</Sequence>

=== nuncio-bitis/SigGen/data/Seq2_desc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Sequence SYSTEM "SequenceDesc.dtd">
<Sequence>
    <Name>Sequence_2</Name>
    <Description>Single signal sequence #2</Description>
    <SampleRate>16000</SampleRate>
    <Signal>
        <Name>Signal_2</Name>
        <Description>Signal #2</Description>
        <Duration>1000</Duration>

        <Tone>
            <amp>1.0</amp>
            <freq>1200</freq>
            <phase>0</phase>
        </Tone>

        <Tone>
            <amp>1.0</amp>
            <freq>1800</freq>
            <phase>90</phase>
        </Tone>

        <Tone>
            <amp>1.0</amp>
            <freq>2100</freq>
            <phase>180</phase>
        </Tone>

        <Tone>
            <amp>1.0</amp>
            <freq>2400</freq>
            <phase>270</phase>
        </Tone>

	</Signal>
</Sequence>

=== nuncio-bitis/SigGen/data/PerfHi2Even_desc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Sequence SYSTEM "SequenceDesc.dtd">
<Sequence>
    <Name>perf-high-even</Name>
    <Description>Perfusion alarm, high priority. Even harmonics.</Description>
    <SampleRate>16000</SampleRate>

    <Signal>
        <Name>Pulse_1</Name>
        <Description>Pulse 1</Description>
        <Duration>100</Duration>
        <RiseFactor>10.0</RiseFactor>
        <FallFactor>50.0</FallFactor>
        <!-- C4 -->
        <Tone>
            <amp>1.0</amp>
            <freq>261.63</freq>
            <phase>0</phase>
            <harmonics>2,4,6,8</harmonics>
            <harmonicAmps>0.5,0.2,0.1,0.05</harmonicAmps>
        </Tone>
    </Signal>

    <Silence>125</Silence>

    <Signal>
        <Name>Pulse_2</Name>
        <Description>Pulse 2</Description>
        <Duration>100</Duration>
        <RiseFactor>10.0</RiseFactor>
        <FallFactor>50.0</FallFactor>
        <!-- F#4 -->
        <Tone>
            <amp>1.0</amp>
            <freq>370.0</freq>
            <phase>0</phase>
            <harmonics>2,4,6,8</harmonics>
            <harmonicAmps>0.5,0.2,0.1,0.05</harmonicAmps>
        </Tone>
    </Signal>

    <Silence>125</Silence>

    <Signal>
        <Name>Pulse_3</Name>
        <Description>Pulse 3</Description>
        <Duration>100</Duration>
        <RiseFactor>10.0</RiseFactor>
        <FallFactor>50.0</FallFactor>
        <!-- C4 -->
        <Tone>
            <amp>1.0</amp>
            <freq>261.63</freq>
            <phase>0</phase>
            <harmonics>2,4,6,8</harmonics>
            <harmonicAmps>0.5,0.2,0.1,0.05</harmonicAmps>
        </Tone>
    </Signal>

    <Silence>400</Silence>

    <Signal>
        <Name>Pulse_4</Name>
        <Description>Pulse 4</Description>
        <Duration>100</Duration>
        <RiseFactor>10.0</RiseFactor>
        <FallFactor>50.0</FallFactor>
        <!-- C4 -->
        <Tone>
            <amp>1.0</amp>
            <freq>261.63</freq>
            <phase>0</phase>
            <harmonics>2,4,6,8</harmonics>
            <harmonicAmps>0.5,0.2,0.1,0.05</harmonicAmps>
        </Tone>
    </Signal>

    <Silence>125</Silence>

    <Signal>
        <Name>Pulse_5</Name>
        <Description>Pulse 5</Description>
        <Duration>100</Duration>
        <RiseFactor>10.0</RiseFactor>
        <FallFactor>50.0</FallFactor>
        <!-- F#4 -->
        <Tone>
            <amp>1.0</amp>
            <freq>370.0</freq>
            <phase>0</phase>
            <harmonics>2,4,6,8</harmonics>
            <harmonicAmps>0.5,0.2,0.1,0.05</harmonicAmps>
        </Tone>
    </Signal>

    <Silence>400</Silence>

</Sequence>
