=== nuncio-bitis/SigGen/data/SequenceDesc.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Define the XML document type of Sequence -->
<!DOCTYPE Sequence [
  <!ELEMENT Sequence (Name,Description,SampleRate,Sequence*,Signal*,DTMF*,Silence*)>

  <!ELEMENT Name (#PCDATA)>
  <!ELEMENT Description (#PCDATA)>
  <!ELEMENT SampleRate (#PCDATA)>
  <!ELEMENT Silence (#PCDATA)>

  <!ELEMENT DTMF (#PCDATA,OnTime,OffTime)>
    <!ELEMENT OnTime (#PCDATA)>
    <!ELEMENT OffTime (#PCDATA)>

  <!ELEMENT Signal (Duration?,Samples?,RiseFactor?,FallFactor?,Tone)>
      <!ELEMENT Duration (#PCDATA)>         <!-- Duration: in milliseconds -->
      <!ELEMENT Samples (#PCDATA)>          <!-- Number of samples (only if Duration not specified) -->
      <!ELEMENT RiseFactor (#PCDATA)>       <!-- Rise and Fall factors: percentage of the duration -->
      <!ELEMENT FallFactor (#PCDATA)>
      <!ELEMENT Tone (amp,freq,phase,harmonics?,harmonicAmps?)>
          <!ELEMENT amp (#PCDATA)>          <!-- Amplitude of fundamental frequency -->
          <!ELEMENT freq (#PCDATA)>
          <!ELEMENT phase (#PCDATA)>
          <!ELEMENT harmonics (#PCDATA)>    <!-- harmonics: List of harmonics. 1 (the fundamental) is implied above -->
          <!ELEMENT harmonicAmps (#PCDATA)> <!-- harmonics: List of harmonics' amplitudes -->
]>
<BODY></BODY>

=== nuncio-bitis/SigGen/data/LP_desc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Sequence SYSTEM "SequenceDesc.dtd">
<Sequence>
    <Name>Modem_LP</Name>
    <Description>Modem line probing tone</Description>
    <SampleRate>16000</SampleRate>
    <Signal>
        <Name>LP</Name>
        <Description>Modem line probing tone</Description>
        <Duration>1000</Duration>

        <Tone>
            <freq>150</freq>
            <phase>0</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>300</freq>
            <phase>180</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>450</freq>
            <phase>0</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>600</freq>
            <phase>0</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>750</freq>
            <phase>0</phase>
            <amp>1.0</amp>
        </Tone>

        <!-- 900 Dropout -->
        
        <Tone>
            <freq>1050</freq>
            <phase>0</phase>
            <amp>1.0</amp>
        </Tone>

        <!-- 1200 Dropout -->

        <Tone>
            <freq>1350</freq>
            <phase>0</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>1500</freq>
            <phase>0</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>1650</freq>
            <phase>180</phase>
            <amp>1.0</amp>
        </Tone>

        <!-- 1800 Dropout --> 

        <Tone>
            <freq>1950</freq>
            <phase>0</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>2100</freq>
            <phase>0</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>2250</freq>
            <phase>180</phase>
            <amp>1.0</amp>
        </Tone>

        <!-- 2400 Dropout --> 

        <Tone>
            <freq>2550</freq>
            <phase>0</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>2700</freq>
            <phase>180</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>2850</freq>
            <phase>0</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>3000</freq>
            <phase>180</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>3150</freq>
            <phase>180</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>3300</freq>
            <phase>180</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>3450</freq>
            <phase>180</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>3600</freq>
            <phase>0</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>3750</freq>
            <phase>0</phase>
            <amp>1.0</amp>
        </Tone>

    </Signal>
</Sequence>

=== nuncio-bitis/SigGen/data/Sig1_desc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Sequence SYSTEM "SequenceDesc.dtd">
<Sequence>
    <Name>Signal_1</Name>
    <Description>Single signal sequence #1</Description>
    <SampleRate>16000</SampleRate>
    <Signal>
        <Name>Signal_1</Name>
        <Description>Signal #1</Description>
        <Duration>1000</Duration>

        <Tone>
            <freq>150</freq>
            <phase>0</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>300</freq>
            <phase>45</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>450</freq>
            <phase>90</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>600</freq>
            <phase>135</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>750</freq>
            <phase>180</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>900</freq>
            <phase>225</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>1050</freq>
            <phase>270</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>1200</freq>
            <phase>315</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>1350</freq>
            <phase>0</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>1500</freq>
            <phase>45</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>1650</freq>
            <phase>90</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>1800</freq>
            <phase>135</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>1950</freq>
            <phase>180</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>2100</freq>
            <phase>225</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>2250</freq>
            <phase>270</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>2400</freq>
            <phase>315</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>2550</freq>
            <phase>0</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>2700</freq>
            <phase>45</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>2850</freq>
            <phase>90</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>3000</freq>
            <phase>135</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>3150</freq>
            <phase>180</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>3300</freq>
            <phase>225</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>3450</freq>
            <phase>270</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>3600</freq>
            <phase>315</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>3750</freq>
            <phase>0</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>3900</freq>
            <phase>45</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>4050</freq>
            <phase>90</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>4200</freq>
            <phase>135</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>4350</freq>
            <phase>180</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>4500</freq>
            <phase>225</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>4650</freq>
            <phase>270</phase>
            <amp>1.0</amp>
        </Tone>

        <Tone>
            <freq>4800</freq>
            <phase>315</phase>
            <amp>1.0</amp>
        </Tone>

    </Signal>
</Sequence>
